swagger: "2.0"
info:
  version: "1.0"
  title: Doodle Mail
  contact: {}
host: localhost:5000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      summary: Connection test
      description: Retrieve a simple test message from the server.
      tags:
        - Doodle Mail
      operationId: Connectiontest
      deprecated: false
      responses:
        "200":
          description: A test message.
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to doodle-mail!
  /rooms/info:
    get:
      summary: Get All Room Info
      tags:
        - Doodle Mail
      operationId: GetAllRoomInfo
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        "200":
          description: "An array of room objects."
          headers: {}
          content:
            application/json:
              schema:
              type: string
              example:
                {
                  "rooms":
                    [
                      {
                        "participants": ["pleb"],
                        "messages": ["608330e010cd25158809b90c"],
                        "_id": "6083307c10cd25158809b90b",
                        "entryCode": "cBSL",
                        "__v": 0,
                      },
                    ],
                }
  /rooms/{roomCode}/info:
    get:
      summary: Get Room Info
      tags:
        - Doodle Mail
      operationId: GetRoomInfo
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: roomCode
          in: path
          required: true
          type: string
          description: ""
      responses:
        "200":
          description: A room object
          headers: {}
          content:
            application/json:
              schema:
                type: string
                example:
                  {
                    "room":
                      {
                        "participants":
                          ["pleb"],
                        "messages":
                          [
                            {
                              "_id": "60870957094e2509b8671159",
                              "author": "pleb",
                              "title": "Test Message 4",
                              "date": "1619462487946",
                              "imageData": "TALKJLASJD",
                              "background": "blue",
                              "__v": 0,
                            },
                          ],
                        "_id": "6086f4f3c251c729b4a041a6",
                        "entryCode": "abcd",
                        "__v": 0,
                      },
                  }
        "400":
          description: Bad request. Missing room code in URL or internal error.
  /rooms:
    post:
      summary: Create Room
      tags:
        - Doodle Mail
      operationId: CreateRoom
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/CreateRoomRequest"
      responses:
        "200":
          description: A room object.
          headers: {}
          content:
            application/json:
              schema:
                type: string
                example:
                  {
                    "room":
                      {
                        "participants": ["pleb"],
                        "messages": [],
                        "_id": "608ac3a16774c31aa8c8082b",
                        "entryCode": "kQ0g",
                        "__v": 0,
                      },
                  }
        "400":
          description: Bad Request. Missing userName in request body or other error.
  /rooms/{roomCode}/join:
    post:
      summary: Join Room
      tags:
        - Doodle Mail
      operationId: JoinRoom
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: roomCode
          in: path
          required: true
          type: string
          description: ""
        - name: Body
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/JoinRoomRequest"
      responses:
        "200":
          description: "A room object."
          headers: {}
          content:
            application/json:
              schema:
                type: string
                example:
                  {
                    "room":
                      {
                        "participants": ["mike", "pleb"],
                        "messages": [],
                        "_id": "6086f4f3c251c729b4a041a6",
                        "entryCode": "vnOk",
                        "__v": 0,
                      },
                  }
        "400":
          description: Bad Request. Missing roomCode in URL params or userName in request body, or user already exists in room.
  /rooms/{roomCode}/leave:
    post:
      summary: Leave Room
      tags:
        - Doodle Mail
      operationId: LeaveRoom
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: roomCode
          in: path
          required: true
          type: string
          description: ""
        - name: Body
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/LeaveRoomRequest"
      responses:
        "200":
          description: "An OK response."
          headers: {}
        "400":
          description: Bad Request. Missing roomCode in URL parameters or userName in request body, or user does not exist in room.
  /rooms/{roomId}/messages:
    get:
      summary: Get Room Messages
      tags:
        - Doodle Mail
      operationId: GetRoomMessages
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: roomId
          in: path
          required: true
          type: string
          description: The room _id
      responses:
        "200":
          description: An array of message objects.
          content:
            application/json:
              schema:
                type: string
                example:
                  [
                    {
                      "_id": "60870957094e2509b8671159",
                      "author": "pleb",
                      "title": "Test Message 4",
                      "date": "1619462487946",
                      "imageData": "TALKJLASJD",
                      "background": "blue",
                      "__v": 0,
                    },
                  ]
        "400":
          description: Bad Request. Missing roomId in URL params or userName in request body, or user is not part of room.
    post:
      summary: Send Message To Room
      tags:
        - Doodle Mail
      operationId: SendMessageToRoom
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: roomId
          in: path
          required: true
          type: string
          description: The room _id
        - name: Body
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/SendMessageToRoomRequest"
      responses:
        "200":
          description: An array containing the room's messages, after adding the newly created message.
          content:
            application/json:
              schema:
                type: string
                example:
                  [
                    {
                      "_id": "60870957094e2509b8671159",
                      "author": "pleb",
                      "title": "Test Message 4",
                      "date": "1619462487946",
                      "imageData": "TALKJLASJD",
                      "background": "blue",
                      "__v": 0,
                    },
                  ]
        "400":
          description: Bad Request. Missing roomId in URL params or userName or message details in request body, or user is not in room.
  /messages:
    delete:
      summary: Delete Message
      tags:
        - Doodle Mail
      operationId: DeleteMessage
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ""
          schema:
            $ref: "#/definitions/DeleteMessageRequest"
      responses:
        "200":
          description: An array containing the room's messages, after adding the newly created message.
          content:
            application/json:
              schema:
                type: string
                example:
                  [
                    {
                      "_id": "60870957094e2509b8671159",
                      "author": "pleb",
                      "title": "Test Message 4",
                      "date": "1619462487946",
                      "imageData": "TALKJLASJD",
                      "background": "blue",
                      "__v": 0,
                    },
                  ]
        "400":
          description: Bad Request. Missing roomId in URL params or userName or message details in request body, or user is not in room.
definitions:
  CreateRoomRequest:
    title: CreateRoomRequest
    example:
      userName: pleb
    type: object
    properties:
      userName:
        type: string
    required:
      - userName
  JoinRoomRequest:
    title: JoinRoomRequest
    example:
      userName: pleb
    type: object
    properties:
      userName:
        type: string
    required:
      - userName
  LeaveRoomRequest:
    title: LeaveRoomRequest
    example:
      userName: pleb
    type: object
    properties:
      userName:
        type: string
    required:
      - userName
  SendMessageToRoomRequest:
    title: SendMessageToRoomRequest
    example:
      userName: pleb
      messages:
        - title: Test Message 4
          imageData: TALKJLASJD
          background: blue
    type: object
    properties:
      userName:
        type: string
      messages:
        type: array
        items:
          $ref: "#/definitions/Message"
    required:
      - userName
      - messages
  Message:
    title: Message
    example:
      title: Test Message 4
      imageData: TALKJLASJD
      background: blue
    type: object
    properties:
      title:
        type: string
      imageData:
        type: string
      background:
        type: string
    required:
      - title
      - imageData
      - background
  DeleteMessageRequest:
    title: DeleteMessageRequest
    example:
      messageId: 608330e010cd25158809b90c
    type: object
    properties:
      messageId:
        type: string
    required:
      - messageId
tags:
  - name: Doodle Mail
    description: ""
